### ISSUE TITLE
Incorrect template for node type upgrade?

### ISSUE THREAD

**Issue by jberezanski-mdg** [microsoft/service-fabric-scripts-and-templates#31]
The [node type upgrade article](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-scale-up-node-type#upgrade-the-size-and-operating-system-of-the-primary-node-type-vms) references the [nodetype-upgrade/Deploy-2NodeTypes-3ScaleSets](https://github.com/microsoft/service-fabric-scripts-and-templates/blob/master/templates/nodetype-upgrade/Deploy-2NodeTypes-3ScaleSets.json) template from this repository. The template is supposed to create **three** VM Scale Sets mapped to **two** SF node types. However, after the recent pull request #30, the template seems broken - the third VMSS references a third node type, which is not present in the SF cluster resource properties and seems to conflict with the point of the article. The pull request does not contain any explanation for the change.

Please confirm the [nodetype-upgrade/Deploy-2NodeTypes-3ScaleSets](https://github.com/microsoft/service-fabric-scripts-and-templates/blob/master/templates/nodetype-upgrade/Deploy-2NodeTypes-3ScaleSets.json) template is correct or revert the change if it is not.

**Comment by markwragg** [comment]
I agree this seems wrong to me, the guide that references these templates indicates that the nodetyperef should be the same for new scaleset in order for it to ultimately replace the current one.

There's also no explanation in that PR as to why the change was made. The updated template also doesn't make sense as a template that would create 3 distinct node types because the nodeTypes section of the `Microsoft.ServiceFabric/clusters` resource hasn't been updated to include it.

PR #30 should be reverted.

**Comment by erikadoyle** [comment]
Thanks for raising the issue. This has now been reverted.
